### PR TITLE
ADAPT-31634 Upgrade Storybook and update pull request template

### PR DESCRIPTION
**Pull request by rebeccahongsf**
# READY FOR REVIEW

# Summary
- Upgrade Storybook and update pull request template

# Needed By (Date)
- Aug 25

# Urgency
- low

# Steps to Test

1. Pull this PR
2. Review code and run locally

# Associated Issues and/or People
-[ ADAPT-3184](https://stanfordits.atlassian.net/browse/ADAPT-3184)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
I guess the checks failed because there are no stories yet (was looking at the logs) 😂  I'm going to approve this since updating Storybook should be fine. It might be a good idea to add a super simple component/story there just to double check, but that could be done once we start working on the first form element 😄  Thank you for updating the PR template too!

**Review by yvonnetangsu — APPROVED** [review]
Approving and we can test when start adding new components. Thank you 😄 !

**Comment by yvonnetangsu** [comment]
Doesn't seem like I can merge 🤔  Would that be a permissions issue or because of the failed checks?

**Comment by rebeccahongsf** [comment]
> Doesn't seem like I can merge 🤔 Would that be a permissions issue or because of the failed checks?

Ah, I forgot to grant you all access to the repo 😢 Definitely a permissions issue. I think the failed checks aren't passing because there are no stories. But I'll make sure all the checks pass once we get stories in (like PR #1 😄 )

**Comment by yvonnetangsu** [comment]
@rebeccahongsf Yay - thank you for setting this up 🥳 !

**Pull request merged**
